### ISSUE TITLE
Please consider making all actions async

### ISSUE THREAD

**Issue by b-s-d** [Jazaret/Nancy#2]
https://github.com/Jazaret/Nancy/blob/949d9f34056d17e22cf6ce9890d0c4c86dff6dda/NancyApplication/Services/AccountService.cs#L20

**Comment by Jazaret** [comment]
The repository calls for upsert methods are async. I can change the Service calls to be async and await the results OR I can call the upsert methods in the repository asynchronously, and handle any exceptions after the fact and return the account object created in the service (optimistically)

Like so:
` _accountRepo.AddAccount(account).ContinueWith(t => {
//handle error
Console.WriteLine(t.Exception);},
        TaskContinuationOptions.OnlyOnFaulted); 
`

**Comment by b-s-d** [comment]
Let's go with the following option:

`Change the Service calls to be async and await the results`

No need to change all the `service` classes, just `AccountService` should be enough to prove the understanding, thanks.

**Comment by Jazaret** [comment]
let me know if commit is acceptable. thank you

**Comment by b-s-d** [comment]
Looks good.
