### ISSUE TITLE
Subscription Confirmation Not Guaranteed in a Multi-Geo Scenario

### ISSUE THREAD

**Issue by b-s-d** [Jazaret/Nancy#3]
https://github.com/Jazaret/Nancy/blob/949d9f34056d17e22cf6ce9890d0c4c86dff6dda/NancyApplication/Services/SubscriptionService.cs#L52

**Comment by b-s-d** [comment]
The READ operation above may fail to find the subscription record, if the WRITE operation was performed using a different CosmosDB client, and to a different node. Although I feel Session Consistency level is the way to go, there is still one missing and important point to guarantee that the READ operation is always performed within the expected scope of consistency.

See below for more details: 
https://blog.jeremylikness.com/cloud-nosql-azure-cosmosdb-consistency-levels-cfe8348686e6

https://stackoverflow.com/questions/50500464/managing-cosmosdb-session-consistency-levels-with-session-token-in-web-environme?rq=1

**Comment by Jazaret** [comment]
So the solution would be to implement saving the session token returned in the write action by saving it to the client, then echoing that session in the read request. By round-tripping the session token, you enforce consistency.

**Comment by b-s-d** [comment]
Precisely.
